openapi: 3.0.0
info:
  title: Local Shoppers Backend
  description: Documentation for the Local Shoppers Backend Service
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v1/docs
    description: local server of our backend service.
