openapi: 3.0.0
info:
  title: Local Shoppers Backend
  description: Documentation for the Local Shoppers Backend Service
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/
    description: local server of our backend service.

paths:
  /hello:
    get:
      summary: "return greet message"
      responses:
        "200":
          description: "return an object"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/login:
    post:
      tags:
        - Users
      summary: "returns an object containing user object and token"
      consumes: application/json
      produces: application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

        description: email address
        in: body
        schema:
          type: string
      responses:
        "200":
          description: "returns an object"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      firstName:
                        type: string
                        example: "zuber"
                      lastName:
                        type: string
                        example: "shekh"
                      email:
                        type: string
                        example: "zuber@example.com"
                  token:
                    type: string
                    example: "textThatNoOneCanUnderstandExceptComputer"

  /users/signup:
    post:
      tags:
        - Users
      summary: "returns an object containing user object and token"
      consumes: application/json
      produces: application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

        description: email address
        in: body
        schema:
          type: string
      responses:
        "200":
          description: "returns an object"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      firstName:
                        type: string
                        example: "zuber"
                      lastName:
                        type: string
                        example: "shekh"
                      email:
                        type: string
                        example: "zuber@example.com"
                  token:
                    type: string
                    example: "textThatNoOneCanUnderstandExceptComputer"
