openapi: 3.0.0
info:
  title: Local Shoppers Backend
  description: Documentation for the Local Shoppers Backend Service
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/
    description: local server of our backend service.

paths:
  /hello:
    get:
      summary: "return greet message"
      responses:
        "200":
          description: "return an object"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
